CREATE DATABASE IF NOT EXISTS NETFLIX;
USE NETFLIX;


CREATE TABLE IF NOT EXISTS STOCKS(
Date date,
Close	double,
High double	,
Low double,
Open double,
Volume int
);
DESCRIBE  NETFLIX_STOCK_DATA;
SELECT * FROM NETFLIX_STOCK_DATA;



SELECT COUNT(*) 
FROM NETFLIX_STOCK_DATA;


SELECT * FROM NETFLIX_STOCK_DATA
WHERE DATE IS NULL;

SELECT * FROM NETFLIX_STOCK_DATA
WHERE CLOSE IS NULL;

-- DATA CLEANING
SELECT * FROM NETFLIX_STOCK_DATA
WHERE DATE IS NULL
      OR
      CLOSE IS NULL
      OR 
      HIGH IS NULL
      OR 
      LOW IS NULL
      OR 
      OPEN IS NULL
      OR 
      VOLUME IS NULL;
      
      
--  DATA EXPLORING 

-- TOTAL STOCKS DATA ENTERED
SELECT COUNT(*) FROM NETFLIX_STOCK_DATA;  

-- TOTAL UNIQUE DATES  
SELECT COUNT(DISTINCT DATE) FROM NETFLIX_STOCK_DATA; 

-- DATA ANALYSIS
SELECT MAX(OPEN)
FROM NETFLIX_STOCK_DATA;

SELECT *
FROM NETFLIX_STOCK_DATA
WHERE CLOSE >1000 AND OPEN >1200;

SELECT DATE ,SUM(CLOSE) AS TOTAL_CLOSE
FROM NETFLIX_STOCK_DATA
WHERE CLOSE >1000 AND OPEN >1200
GROUP BY DATE;

SELECT MAX(DATE) AS LATEST_DATE ,CLOSE , SUM(CLOSE) AS TOTAL_CLOSE
FROM NETFLIX_STOCK_DATA
WHERE CLOSE >1000 AND OPEN >1200
GROUP BY CLOSE;
     
     
     


 


